### ISSUE TITLE
The README could use a table of contents, and some organizational changes.

### ISSUE THREAD

**Issue by pangdaxing23** [hot-glue-for-rails/hot-glue#170]
Would greatly aid navigation.

Also the version history could go in a CHANGELOG.md, it's probably not necessary when learning to use the gem for the first time.

**Comment by jasonfb** [comment]
![hot-glue-for-rails:hot-glue: Rapid scaffold builder for Turbo-Rails and Hotwire  Get the tutorial now at: 2024-12-14 09-14-04](https://github.com/user-attachments/assets/a4ffe9e9-ab31-47c8-b98d-07d0b518b985)
